### PR TITLE
fix(web): route remaining crypto.randomUUID calls through utils/uuid (#1620)

### LINKED ISSUE #1620: Web app fails to load over plain HTTP / LAN IP again after PR #1428 (unguarded crypto.randomUUID in analytics provider)
## Regression

The original symptom from #849 / #394 — "Create button does nothing on plain-HTTP LAN deployments" — has resurfaced as a broader breakage: the entire web app shell now fails to mount on non-secure-context origins (plain HTTP + non-localhost, e.g. `http://192.168.1.x:7456`, the standard Docker / NAS / unRAID self-hosted setup).

PR #900 fixed the original report by introducing `apps/web/src/utils/uuid.ts`, a tiered v4-UUID helper that degrades from `crypto.randomUUID()` → `crypto.getRandomValues()` → `Math.random()` so non-secure contexts get a working ID generator.

PR #1428 (PostHog product analytics) introduced three new `crypto.randomUUID()` call sites in `apps/web/src/analytics/provider.tsx` that bypass the helper. `apps/web/src/runtime/exports.ts:527` carries a fourth from older PDF-export work.

On a non-secure context, Chromium silently makes `crypto.randomUUID` `undefined`, so these calls throw `TypeError: crypto.randomUUID is not a function`. Because `<AnalyticsProvider>` wraps the app and calls `newRequestId()` during render, the exception unwinds out of React before any UI mounts.

## Reproduce

1. Run the daemon and web build on a LAN host (e.g. via Docker) so the app is served at `http://<lan-ip>:<port>` rather than `localhost`.
2. Open that URL in Chrome / Edge / any Chromium-based browser.
3. Observe a blank page (or the React error overlay in dev mode) and the console error:

```
TypeError: crypto.randomUUID is not a function
    at AnalyticsProvider (analytics/provider.tsx)
```

PDF export from the Share menu also fails on the same origins because the print-ready handshake nonce in `runtime/exports.ts` hits the same API.

## Unguarded call sites

- `apps/web/src/analytics/provider.tsx:205` — `insertId` fallback in `track`
- `apps/web/src/analytics/provider.tsx:286` — `newRequestId` in the live provider value
- `apps/web/src/analytics/provider.tsx:306` — `newRequestId` in the no-op stub
- `apps/web/src/runtime/exports.ts:527` — print-ready handshake nonce

## Fix

Route all four sites through the existing `randomUUID()` helper in `apps/web/src/utils/uuid.ts`. PR coming.

## Related

- #849 — original "Create button silently does nothing" bug
- #394 — Chinese duplicate of #849
- #900 — fix that introduced `utils/uuid.ts`
- #1428 — PR that reintroduced the regression

### PR DESCRIPTION
**Pull request by whoughton**
Fixes #1620

## Why

I hit this on my own self-hosted deployment (`http://192.168.1.48:7456`, the
Docker → TrueNAS path). After pulling main I get a blank page and the console
shows `TypeError: crypto.randomUUID is not a function` from inside
`<AnalyticsProvider>`. PR #900 added `apps/web/src/utils/uuid.ts` precisely
to dodge this — `crypto.randomUUID` is restricted to secure contexts
(HTTPS or `localhost`), and plain-HTTP LAN IPs are the standard Docker /
NAS / unRAID self-hosted setup. The helper degrades to
`crypto.getRandomValues` and ultimately `Math.random` so callers always
get a usable v4 UUID.

PR #1428 (PostHog product analytics) added three unguarded
`crypto.randomUUID()` calls in `apps/web/src/analytics/provider.tsx` that
bypass the helper, and `apps/web/src/runtime/exports.ts` had a fourth
from older PDF-export work. On a non-secure context those calls throw
during `<AnalyticsProvider>` rendering and take the whole app shell down
before any UI mounts. PDF export from the Share menu also fails on the
same origins.

#1620 has the full reproduction and call-site list.

## What users will see

- Self-hosted plain-HTTP / LAN-IP deployments (Docker, NAS, unRAID, etc.)
  load the app again. The blank-page regression introduced by #1428 is
  gone.
- PDF export from the Share menu works again on those same deployments.
- No visible behavior change on `localhost` or HTTPS — those origins
  were always taking the `crypto.randomUUID()` branch of the helper
  anyway, so the output is identical.

## Surface area

- [ ] **UI**
- [ ] **Keyboard shortcut**
- [ ] **CLI / env var**
- [ ] **API / contract**
- [ ] **Extension point**
- [ ] **i18n keys**
- [ ] **New top-level dependency**
- [x] **Default behavior change** — self-hosted plain-HTTP / LAN-IP deployments stop crashing on load; no visible change for users on `localhost` / HTTPS.
- [ ] **None**

## Bug fix verification

This is mechanical: replace four `crypto.randomUUID()` callers with the
existing tiered helper from `apps/web/src/utils/uuid.ts`. A red spec
would have to fake a non-secure-context environment in JSDOM (delete
`globalThis.crypto.randomUUID` for the duration of an
`<AnalyticsProvider>` render) — happy to add one if reviewers want it,
but the helper itself is already covered by the original #900 work.

- Test path that reproduces the bug: n/a (covered manually against the
  affected deployment; see verification below).
- Did the test go red on `main` and green on this branch? n/a
- Manual verification: rebuilt the Docker image, redeployed, the app
  shell now mounts on `http://<lan-ip>:7456` instead of throwing on
  load.

## Validation

- `pnpm guard` — pass
- `pnpm --filter @open-design/web typecheck` — pass
- `pnpm --filter @open-design/web test analytics` — pass (14/14)
- Manual smoke against `http://192.168.1.48:7456` — app mounts, no
  console crypto error, PDF export works.

Pre-existing test failures on `origin/main` in
`AssistantMessage.test.tsx`, `DesignsTab.select-mode.test.tsx`,
`SettingsDialog.execution.test.tsx`, and
`Theater/hooks/useCritiqueTheaterEnabled.test.tsx` reproduce on `main`
before this branch and are unrelated to this change.

### CODE REVIEW

**Review by lefarcen — COMMENTED** [review]
Hi @whoughton — this is a very focused fix, and the PR write-up made the regression path easy to follow. Routing the analytics request IDs and the PDF export nonce through the existing `randomUUID()` helper is the right shape for the plain-HTTP LAN/self-hosted case.

I read the touched files, the linked issue, the existing UUID helper coverage, and the runtime export tests. I don’t see a blocking code issue in this patch. The only follow-up I’d consider is adding call-site regression coverage later so future analytics/export work can’t reintroduce direct `crypto.randomUUID()` usage in these non-secure-context paths, but I’m not blocking this small fix on that.

Product review is also requested because the PR marks a user-visible default-behavior change. Thanks for the crisp report and patch — this should be straightforward for the next reviewer to validate. 🙌

**Review by mrcfps — APPROVED** [review]
@whoughton I reviewed the changed call sites in `apps/web/src/analytics/provider.tsx` and `apps/web/src/runtime/exports.ts`, and routing them through the existing `randomUUID()` helper looks correct for the non-secure-context regression this PR is fixing. I also checked the existing UUID helper coverage and the PDF export handshake tests, and this patch stays tightly scoped to the four remaining direct `crypto.randomUUID()` usages. Thanks for the focused fix here — this should make the plain-HTTP self-hosted path much safer against regressions. 🙌


<sub>🔁 Powered by <a href="https://github.com/nexu-io/looper">Looper</a> · runner=reviewer · agent=opencode · An autonomous AI dev team for your GitHub repos.</sub>

**Comment by lefarcen** [comment]
Heads-up: PR #1644 (by @xxiaoxiong, opened ~2h after yours) is also open against this area — both PRs touch the exact same files (`apps/web/src/analytics/provider.tsx` and `apps/web/src/runtime/exports.ts`) and address issue #1620's crypto.randomUUID secure-context regression.

You and @xxiaoxiong might want to compare approaches; the maintainer team will pick which lands. Sharing so neither effort gets wasted.

**Comment by leilei926524-tech** [comment]
Hi @whoughton!

Your first Open Design PR has been merged! Huge thanks for jumping in and improving the project!

You contributed:

Merged PR: #1621 fix(web): route remaining crypto.randomUUID calls through utils/uuid (#1620)
https://github.com/nexu-io/open-design/pull/1621

That is a real contribution to Open Design, and we would love to help you keep the momentum going!

For your next contribution, we picked two issues that look like a good follow-up:

1. #2206 Local CLI startup path can overflow the chat status card
https://github.com/nexu-io/open-design/issues/2206

2. #2079 Plugins tab and page are not localized in Chinese
https://github.com/nexu-io/open-design/issues/2079

If one of these looks interesting, feel free to comment /claim on the issue and we will help you get started!

Once your second PR gets merged, you will move into our Continuous Contributor tier. We are also starting to highlight repeat contributors more actively in the community, so this is a great time to keep going!

Thanks again for the first PR, and welcome to the Open Design contributor community!

The Open Design team

P.S. We hang out in Discord — come say hi: https://discord.gg/3C6EWXbdQQ
There's a #contributors channel where folks share what they're working on.

**Comment by leilei926524-tech** [comment]
Hi @whoughton!

Your first Open Design PR has been merged! Huge thanks for jumping in and improving the project!

You contributed:

Merged PR: #1621 fix(web): route remaining crypto.randomUUID calls through utils/uuid (#1620)
https://github.com/nexu-io/open-design/pull/1621

Your PR touched the web experience around fix(web): route remaining crypto.randomuuid calls through utils/uuid (#1620), so the follow-up issues below should feel close to the same surface area.

For your next contribution, we picked two issues that look like a good follow-up:

1. #2510 Home tab should be singleton instead of duplicating after returning from projects
https://github.com/nexu-io/open-design/issues/2510

This looks like a reasonable follow-up because it stays close to the web area while still being scoped as a good first issue.

2. #2395 Polish connector detail panel layout and visual hierarchy
https://github.com/nexu-io/open-design/issues/2395

This looks like a reasonable follow-up because it stays close to the web area while still being scoped as a good first issue.

If one of these looks interesting, feel free to comment /claim on the issue and we will help you get started!

Once your second PR gets merged, you will move into our Continuous Contributor tier. We are also starting to highlight repeat contributors more actively in the community, so this is a great time to keep going!

Thanks again for the first PR, and welcome to the Open Design contributor community!

The Open Design team

P.S. We hang out in Discord — come say hi: https://discord.gg/3C6EWXbdQQ
There's a #contributors channel where folks share what they're working on.
