### PR TITLE
fix(i18n): add missing designFiles.showMore key to ar/hu/ko/pl/tr

### PR DESCRIPTION
**Pull request by lefarcen**
## Summary

PR #239 added the `designFiles.showMore` key to `en.ts` and 8 other locales but missed **ar, hu, ko, pl, tr**, leaving `pnpm --filter @open-design/web typecheck` red on `main` (TS2741 × 5):

```
src/i18n/locales/ar.ts(3,14): error TS2741: Property ''designFiles.showMore'' is missing
src/i18n/locales/hu.ts(3,14): error TS2741: Property ''designFiles.showMore'' is missing
src/i18n/locales/ko.ts(3,14): error TS2741: Property ''designFiles.showMore'' is missing
src/i18n/locales/pl.ts(3,14): error TS2741: Property ''designFiles.showMore'' is missing
src/i18n/locales/tr.ts(3,14): error TS2741: Property ''designFiles.showMore'' is missing
```

This fails CI on every PR opened off `main` since #239 (commit `b06021c`) landed.

This PR adds the key to the 5 missing locales with native translations, following the verb/counter conventions PR #239 used in the locales it did update. Native speakers welcome to refine.

| Locale | Value | Notes |
|---|---|---|
| ar | `عرض +{n} أخرى` | "show +{n} other" |
| hu | `+{n} további megjelenítése` | matches German verb-final pattern |
| ko | `+{n}개 더 보기` | standard `개` counter + `더 보기` |
| pl | `Pokaż +{n} więcej` | matches es/pt-BR verb-first pattern |
| tr | `+{n} tane daha göster` | counter `tane` + `daha göster` |

## Test plan

- [x] `pnpm --filter @open-design/web typecheck` — clean
- [x] `pnpm --filter @open-design/web test` — 131/131 pass (incl. `locales.test.ts` placeholder-alignment check)
- [x] No other locale files touched

### CODE REVIEW

**Review by lefarcen — COMMENTED** [review]
**Code review (Lens A — type safety + test coverage)**:

✅ **ar, hu, ko, pl**: All 4 additions are correct. Each:
  - Uses the exact placeholder `{n}` matching `en.ts`
  - Inserts alphabetically between `sectionOther` and `kindHtml`
  - Passes `locales.test.ts` placeholder alignment check
  - Follows verb/counter conventions consistent with sibling locales

⚠️ **tr (Turkish)**: This locale file exists but is **not registered** in `apps/web/src/i18n/types.ts` (neither in the `Locale` union type nor the `LOCALES` array). Consequence:
  - The `tr.ts` file is never imported in production
  - The test file only validates the 13 registered locales (see `EXPECTED_LOCALES` in `locales.test.ts`)
  - Adding keys to `tr.ts` has **zero runtime effect**

If Turkish should be a supported locale, it needs:
  1. Addition to the `Locale` type union in `types.ts`
  2. Addition to the `LOCALES` array
  3. Addition to `LOCALE_LABEL` with `'tr': 'Türkçe'`
  4. Addition to `EXPECTED_LOCALES` in `locales.test.ts`

If Turkish is intentionally **not** a supported locale (e.g., leftover from an old branch or future work), then the entire `tr.ts` file should be deleted to avoid confusion.

**Reasoning completeness (Lens B)**:

The PR body correctly identifies the root cause (PR #239 missed these locales), links the breaking commit (`b06021c`), and provides a clear test plan. However:

- **Scope claim mismatch**: The title says "ar/hu/ko/pl/tr" (5 locales) but only 4 are actually *missing* from the registered set. The 5th (tr) was never part of the active locale list.
- **Translation sourcing**: No provenance given (AI-assisted? reviewed by native speakers? crowd-sourced?). For future i18n PRs, consider documenting this in the PR template.

**Overall**: The 4 real fixes (ar, hu, ko, pl) are clean and unblock CI. The tr addition is harmless but pointless unless Turkish becomes a registered locale. LGTM for merge as-is; follow-up decision on tr.ts can happen separately.
